[package]
name = "db-utils"
description = "Utilities used as Clickhouse UDF."
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "compute-height"
path = "src/compute-height.rs"
test = false
bench = false

[[bin]]
name = "compute-localtime"
path = "src/compute-localtime.rs"
test = false
bench = false

[dependencies]
clap.workspace = true
eyre.workspace = true
jiff.workspace = true

egm2008 = "0.1"
log = "0.4"
