[workspace]
resolver = "2"
members = ["acutectl", "fetiched", "formats", "sources", "opensky-history"]
exclude = ["cat21conv"]

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.10"
eyre = { version = "0.6", features = ["auto-install", "track-caller"] }
fetiche-formats = { version = "0", path = "formats" }
fetiche-sources = { version = "0", path = "sources" }
hcl-rs = "0.16"
home = "0.5"
influxdb = { version = "0.7", features = ["derive"] }
log = { version = "0.4", features = ["serde", "std"] }
nom = "7"
opentelemetry = { version = "0.21", features = ["logs", "metrics"] }
opentelemetry-jaeger = { version = "0.20", features = ["rt-tokio", "reqwest_blocking_collector_client"] }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
progress = "0.2"
reqwest = { version = "0.11", features = ["blocking", "gzip", "json", "serde_json", "socks", "deflate"] }
rstest = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = { version = "3", features = ["base64", "chrono", "json", "hex"] }
strum = { version = "0", features = ["derive"] }
tabled = "0.14"
tracing = "0.1"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry", "time", "tracing"] }
tracing-tree = { version = "0.2", features = ["time"] }
