[workspace]
members = ["common", "fetiched", "formats", "sources", "acutectl", "process-data", "common"]
default-members = ["acutectl", "process-data"]
exclude = ["adsb-to-parquet", "opensky-history"]
resolver = "2"

[workspace.dependencies]
arrow2 = { version = "0.17", features = ["io_csv", "io_json", "io_json_integration", "io_parquet"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["cargo", "derive"] }
criterion = { version = "0.5", features = ["async_tokio"] }
csv = "1.3"
datafusion = { version = "41.0", features = ["zstd", "async-compression", "serde"] }
dateparser = "0.2"
directories = "5"
env_logger = "0.11"
eyre = { version = "0.6", features = ["auto-install", "track-caller"] }
fetiche-common = { version = "0", path = "common" }
fetiche-formats = { version = "0", path = "formats" }
fetiche-macros = { version = "0", path = "macros" }
fetiche-sources = { version = "0", path = "sources" }
hcl-rs = "0.18"
home = "0.5"
log = { version = "0.4", features = ["serde", "std"] }
nom = "7"
opentelemetry = { version = "0.24", features = ["logs", "metrics"] }
opentelemetry-otlp = "0.17"
opentelemetry_sdk = { version = "0.24", features = ["rt-tokio"] }
parquet2 = { version = "0.17", features = ["zstd"] }
progress = "0.2"
reqwest = { version = "0.12", features = ["blocking", "gzip", "json", "socks", "deflate"] }
rstest = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_arrow = { version = "0.11", features = ["arrow2-0-17"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = { version = "3", features = ["base64", "chrono_0_4", "json", "hex"] }
strum = { version = "0.26", features = ["derive"] }
tabled = "0.16"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-log = "0.2"
tracing-opentelemetry = "0.25"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry", "time", "tracing"] }
tracing-tree = { version = "0.4", features = ["time"] }
