[workspace]
resolver = "2"
members = ["acutectl", "engine", "fetiched", "formats", "sources", "opensky-history"]
exclude = ["cat21conv"]

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.10"
eyre = { version = "0.6", features = ["auto-install", "track-caller"] }
fetiche-engine = { version = "0", path = "engine" }
fetiche-formats = { version = "0", path = "formats" }
fetiche-sources = { version = "0", path = "sources" }
hcl-rs = "0.15"
home = "0.5"
log = { version = "0.4", features = ["serde", "std"] }
nom = "7"
reqwest = { version = "0.11", features = ["blocking", "gzip", "json", "serde_json", "socks", "deflate"] }
rstest = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
strum = { version = "0", features = ["derive"] }
tabled = "0.13"
tracing = "0.1"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry", "time", "tracing"] }
