[workspace]
members = ["common", "client", "engine", "cmd/fetiched", "formats", "acutectl", "process-data", "cmd/convert-from-json", "cmd/find-airport", "db-utils", "cmd/opensky-history"]
default-members = ["acutectl", "process-data", "cmd/convert-from-json", "cmd/find-airport", "cmd/opensky-history", "db-utils"]

resolver = "2"

[workspace.dependencies]
chrono = { version = "0.4.41", features = ["serde", "std", "rkyv-32", "rkyv-validation"] }
clap = { version = "4", features = ["cargo", "derive"] }
criterion = { version = "0.8", features = ["async", "async_tokio", "async_futures"] }
csv = "1.4"
dateparser = "0.3.1"
derive_builder = "0.20"
directories = "6"
env_logger = "0.11"
eyre = { version = "0.6", features = ["auto-install", "track-caller"] }
fetiche-client = { version = "0", path = "client" }
fetiche-common = { version = "0", path = "common" }
fetiche-engine = { version = "0", path = "engine" }
fetiche-formats = { version = "0", path = "formats" }
fetiche-macros = { version = "0", path = "macros" }
futures = "0.3"
hcl-rs = "0.19"
itertools = "0.14.0"
jiff = { version = "0.2", features = ["serde"] }
nom = "8"
object_store = "0.13"
polars = { version = "0.53", features = ["async", "serde", "lazy", "sql", "strings", "parquet", "json", "dtype-categorical", "temporal"] }
proptest = "1.11"
ractor = { version = "0.15", features = ["async-trait", "serde"] }
reqwest = { version = "0.13", features = ["blocking", "gzip", "json", "socks", "deflate"] }
rstest = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = { version = "3", features = ["base64", "chrono_0_4", "json", "hex"] }
strum = { version = "0.28", features = ["derive"] }
tabled = "0.20"
tempfile = "3"
thiserror = "2.0"
tokio = { version = "1", features = ["parking_lot", "sync", "macros", "io-util", "rt", "rt-multi-thread", "time", "tracing"] }
tracing = "0.1"
