[workspace]
members = ["acutectl", "cat21conv", "curves", "engine", "formats", "sources"]

[workspace.dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.10"
fetiche-engine = { version = "0", path = "engine" }
fetiche-formats = { version = "0", path = "formats" }
fetiche-sources = { version = "0", path = "sources" }
hcl-rs = "0.14"
home = "0.5"
log = { version = "0.4", features = ["serde", "std"] }
reqwest = { version = "0.11", features = ["blocking", "gzip", "json", "serde_json", "socks", "deflate"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
