[package]
name = "fetiche-engine"
version = "0.8.1"
edition = "2021"
authors = ["Ollivier Robert <ollivier.robert@eurocontrol.int>"]
description = "Engine component of Fetiche."
readme = "README.md"
license = "MIT"
repository = "https://github.com/keltia/fetiche-rs"
categories = ["aerospace::drones", "aerospace"]
keywords = ["aeronautical-data", "transformations", "fetiche"]

[features]
default = ["privacy"]
privacy = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre.workspace = true
chrono.workspace = true
env_logger.workspace = true
fetiche-formats.workspace = true
fetiche-sources.workspace = true
hcl-rs.workspace = true
home.workspace = true
log.workspace = true
nom.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tabled.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true

engine-macros = { version = "0", path = "macros" }

async-trait = "0.1"
uuid = { version = "1.3", features = ["v4", "v7"] }
tokio = { version = "1.28", features = ["full"] }

[target.'cfg(unix)'.dependencies]
daemonize = "0.5"

[dev-dependencies]
rstest.workspace = true
