[package]
name = "convert-from-json"
version = "0.1.0"
edition = "2024"
authors = ["Ollivier Robert <ollivier.robert@eurocontrol.int>"]
description = "Load JSON from Avionix and output as CSV/Parquet."
readme = "README.md"
license = "MIT"
repository = "https://github.com/keltia/fetiche-rs"
categories = ["aerospace::drones"]
keywords = ["avionix", "drones", "aeronautical-data"]
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
eyre.workspace = true

chrono = { version = "0.4", features = ["serde", "std"] }
polars-io = { version = "0.54", features = ["csv", "json", "parquet", "zstd"] }
polars-utils = "0.54"
