[package]
name = "fetiche-sources"
version = "0.7.0"
edition = "2021"
authors = ["Ollivier Robert <ollivier.robert@eurocontrol.int>"]
description = "Fetiche component for access methods to connect/fetch data."
readme = "README.md"
license = "MIT"
repository = "https://github.com/keltia/drone-gencsv"
categories = ["aerospace::drones"]
keywords = ["cat21", "asterix", "drones", "aeronautical-data", "hcl", "fetiche"]

[features]
default = ["privacy"]
privacy = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
fetiche-formats.workspace = true
hcl-rs.workspace = true
home.workspace = true
log.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

csv = "1.1"
mini-moka = "0.10"
percent-encoding = "2.2"
serde_repr = "0.1"
tabled = "0.12"
signal-hook = "0.3"

[dev-dependencies]
httpmock = { version = "0.6", features = ["colored", "color", "clap"] }
rstest = "0"
