[package]
name = "fetiched"
version = "0.1.0"
edition = "2021"
description = "Daemon component of Fetiche."

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
fetiche-engine.workspace = true
fetiche-sources.workspace = true
hcl-rs.workspace = true
home.workspace = true
log.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tabled.workspace = true
tracing.workspace = true
tracing-log.workspace = true

nom = "7"
uuid = { version = "1.3", features = ["v4", "v7"] }
tokio = { version = "1.28", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "tracing"] }

[target.'cfg(unix)'.dependencies]
daemonize = "0.5"

[dev-dependencies]
assert_cmd = "2.0"
rstest.workspace = true

