[package]
name = "opensky-history"
version = "0.2.0"
edition = "2021"
authors = ["Ollivier Robert <ollivier.robert@eurocontrol.int>"]
description = "Rust CLI app to fetch historical data through pyopensky."
readme = "README.md"
license = "MIT"
repository = "https://github.com/keltia/fetiche-rs"
categories = ["aerospace::drones", "aerospace"]
keywords = ["aeronautical-data", "transformations", "fetiche", "python", "opensky"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "version"

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono.workspace = true
clap.workspace = true
dateparser.workspace = true
eyre.workspace = true
fetiche-formats.workspace = true
hcl-rs.workspace = true
home.workspace = true
opentelemetry.workspace = true
opentelemetry-jaeger.workspace = true
opentelemetry_sdk.workspace = true
progress.workspace = true
serde.workspace = true
serde_repr.workspace = true
strum.workspace = true
tabled.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing-tree.workspace = true

datafusion = { version = "35.0", features = ["zstd"] }
inline-python = "0.12"
seek_bufread = "1.2"
seekable_reader = "0.1"
tempfile = "3"

[dev-dependencies]
rstest.workspace = true

[dependencies.pyo3]
version = "0.19"
features = ["auto-initialize"]

