[package]
name = "find-airport"
version = "0.2.0"
edition = "2024"
authors = ["Ollivier Robert <ollivier.robert@eurocontrol.int>"]
description = "Fetch OurAirports data into Parquet, and search it."
readme = "README.md"
license = "MIT"
repository = "https://github.com/keltia/fetiche-rs"
categories = ["aerospace", "command-line-utilities"]
keywords = ["opendata", "airport", "aeronautical-data"]
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

[[bench]]
name = "bycountry"
harness = false

[[bench]]
name = "deserialize"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
csv.workspace = true
eyre.workspace = true
fetiche-common.workspace = true
fetiche-macros.workspace = true
futures.workspace = true
jiff.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tabled.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

chrono = { version = "0.4", features = ["serde", "std"] }
farben = "0.20"
pluscodes = "0.5"
polars = { version = "0.54", features = ["async", "serde", "lazy", "sql", "strings", "parquet", "json", "dtype-categorical", "temporal"] }
polars-utils = "0.54"
rayon = "1.12"

[dev-dependencies]
divan = "0.1"
itertools.workspace = true
rstest.workspace = true
