default = "none"

[sites.someplace]

format = "aeroscope"
auth = "aeroscope"
base_url = "http://127.0.0.1:2400"
token = "/login"
login = "SOMETHING"
password = "NOPE"
get = "/drone/get"

[sites.else]

format = "safesky"
auth = "safesky"
base_url = "http://example.net:2400"
token = "/api/security/login"
login = "USER"
password = "MAYBE"
get = "/api/journeys/csv"

[sites.nope]

format = "safesky"
base_url = "https://kansas.example.net:3000"
get = "/somewhere/over/the/rainbow"
