default = "none"

[sites.eih]

format = "aeroscope"
base_url = "http://127.0.0.1:2400"
token = "/login"
login = "SOMETHING"
password = "NOPE"
get = "/drone/get"
prefetch = false

[sites.asd]

format = "asd"
base_url = "https://eur.airspacedrone.com"
login = "USERNAME"
password = "GUESS"
get = "/api/journeys/filteredlocations"
prefetch = false

[sites.safesky]

format = "safesky"
base_url = "https://public-api.safesky.app"
api_key = "foobar"
get = "/beacons"
prefetch = false

[sites.nope]

format = "aeroscope"
base_url = "https://kansas.example.net:3000"
get = "/somewhere/over/the/rainbow"
prefetch = false
